add continuous check with timeout

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -28,7 +28,7 @@ jobs:
                     sudo apt install --yes curl
                     curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
                     sudo apt update
-                    sudo apt install --yes ros-melodic-ros-base
+                    sudo apt install --yes ros-melodic-ros-core
 
                     set +u
                     source /opt/ros/melodic/setup.bash
@@ -36,42 +36,64 @@ jobs:
 
                     check_node() {
                         local node_name=$1
+                        local timeout=$3
+                        local start_time=$(date +%s)
                         local error_code=0
 
-                        error_code=$(rosnode list | grep -q "/$node_name"; echo $?)
-                        if [ error_code? -eq 0 ]; then
-                            echo "$node_name is running."
-                        else
-                            echo "Error - $node_name is not running."
-                            kill $pid
-                            exit 1
-                        fi
+                        while true; do
+                            error_code=$(rosnode list | grep -q "/$name"; echo $?)
+                            if [ $error_code -eq 0 ]; then
+                                echo "$name is running."
+                                return 0
+                            fi
+
+                            local current_time=$(date +%s)
+                            local elapsed_time=$((current_time - start_time))
+
+                            if [ $elapsed_time -ge $timeout ]; then
+                                echo "Error $name is not running."
+                                sudo snap stop turtlebot3c-bringup
+                                exit 1
+                            fi
+                            sleep 1
+                        done
                     }
 
                     check_topic() {
                         local topic_name=$1
                         local pub_name=$2
                         local sub_name=$3
+                        local timeout=$3
+                        local start_time=$(date +%s)
                         local error_code=0
 
-                        error_code=$(rostopic info /$topic_name | grep -E "$pub_name|$sub_name"; echo $?)
-                        if [ error_code? -eq 0 ]; then
-                            echo "$topic_name has publisher $pub_name and subscriber $sub_name."
-                        else
-                            echo "Error - $topic_name does not have pub/sub"
-                            kill $pid
-                            exit 1
-                        fi
+                        while true; do
+                            error_code=$(rostopic info /$topic_name | grep -E "$pub_name|$sub_name"; echo $?)
+                            if [ $error_code -eq 0 ]; then
+                                echo "$topic_name has publisher $pub_name and subscriber $sub_name."
+                                return 0
+                            fi
+
+                            local current_time=$(date +%s)
+                            local elapsed_time=$((current_time - start_time))
+
+                            if [ $elapsed_time -ge $timeout ]; then
+                                echo "Error - $topic_name does not have pub/sub"
+                                kill $pid
+                                exit 1
+                            fi
+                            sleep 1
+                        done
                     }
 
                     ros-talker-listener &
                     pid=$!
 
-                    sleep 30
+                    sleep 20
 
-                    check_node talker
-                    check_node listener
-                    check_topic chatter talker listener
+                    check_node talker 30
+                    check_node listener 30
+                    check_topic chatter talker listener 30
                     kill $pid
 
                     echo "All checks passed successfully."
