add ROS melodic talker listener test

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -1,7 +1,5 @@
 name: snap
 on:
-  schedule:
-    - cron: '0 0 1 * *'
   push:
     tags:
       - '*'
@@ -13,22 +11,51 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    outputs:
-      snap-file: ${{ steps.build-snap.outputs.snap }}
-    steps:
-    - uses: actions/checkout@v2
-    - uses: snapcore/action-build@v1
-      id: build-snap
+  main-snap:
+    uses: ubuntu-robotics/snap_workflows/.github/workflows/build-install-test-snap.yaml@main
+    with:
+      ubuntu-image: ubuntu-18.04
+      branch-name: master
+      snap-name: ros-talker-listener
+      snap-install-args: --devmode
+      test-script: |
+                    #!/bin/bash
+                    
+                    ## Install ROS
+                    sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
 
-    # Make sure the snap is installable
-    - run: |
-        sudo snap install ${{ steps.build-snap.outputs.snap }} --devmode
-    # Do some testing with the snap
-    - run: |
-        snap info ros-talker-listener
-    - uses: actions/upload-artifact@v3
-      with:
-        name: ros-talker-listener
-        path: ${{ steps.build-snap.outputs.snap }}
+                    sudo apt install curl
+                    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
+                    sudo apt update
+                    sudo apt install ros-melodic-ros-base
+
+                    check_node() {
+                        local node_name=$1
+                        rosnode list | grep -q "/$node_name"
+                        if [ $? -eq 0 ]; then
+                            echo "$node_name is running."
+                        else
+                            echo "Error - $node_name is not running."
+                            exit 1
+                        fi
+                    }
+                    check_topic() {
+                        local topic_name=$1
+                        local pub_count=$(rostopic info /$topic_name | grep "Publisher count:" | awk '{print $3}')
+                        local sub_count=$(rostopic info /$topic_name | grep "Subscription count:" | awk '{print $3}')
+                        if [ "$pub_count" -gt 0 ] && [ "$sub_count" -gt 0 ]; then
+                            echo "$topic_name has publishers and subscribers."
+                        else
+                            echo "Error - $topic_name has no publishers or subscribers."
+                            exit 1
+                        fi
+                    }
+
+                    ros-talker-listener &
+                    pid=$!
+                    check_node talker
+                    check_node listener
+                    check_topic chatter
+                    kill $pid
+
+                    echo "All checks passed successfully."
