fix indentation

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -35,28 +35,28 @@ jobs:
                     set -u
 
                     check_node() {
-                        local node_name=$1
-                        local timeout=$2
-                        local start_time=$(date +%s)
-                        local error_code=0
+                      local node_name=$1
+                      local timeout=$2
+                      local start_time=$(date +%s)
+                      local error_code=0
 
-                        while true; do
-                            error_code=$(rosnode list | grep -q "/$node_name"; echo $?)
-                            if [ $error_code -eq 0 ]; then
-                                echo "$node_name is running."
-                                return 0
-                            fi
+                      while true; do
+                        error_code=$(rosnode list | grep -q "/$node_name"; echo $?)
+                          if [ $error_code -eq 0 ]; then
+                            echo "$node_name is running."
+                            return 0
+                          fi
 
-                            local current_time=$(date +%s)
-                            local elapsed_time=$((current_time - start_time))
+                          local current_time=$(date +%s)
+                          local elapsed_time=$((current_time - start_time))
 
-                            if [ $elapsed_time -ge $timeout ]; then
-                                echo "Error $node_name is not running."
-                                sudo snap stop turtlebot3c-bringup
-                                exit 1
-                            fi
-                            sleep 1
-                        done
+                          if [ $elapsed_time -ge $timeout ]; then
+                            echo "Error $node_name is not running."
+                            sudo snap stop turtlebot3c-bringup
+                            exit 1
+                          fi
+                          sleep 1
+                      done
                     }
 
                     check_topic() {
