run workflow in lxc container

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -12,9 +12,9 @@ on:
 
 jobs:
   main-snap:
-    uses: ubuntu-robotics/snap_workflows/.github/workflows/build-install-test-snap.yaml@F_add_snapcraft_channel_option
+    uses: ubuntu-robotics/snap_workflows/.github/workflows/build-install-test-snap-lxc.yaml@F_add_lxc_template
     with:
-      ubuntu-image: ubuntu-20.04
+      lxc-image: ubuntu:18.04
       snapcraft-channel: 7.x
       branch-name: master
       snap-name: ros-talker-listener
@@ -28,9 +28,9 @@ jobs:
                     sudo apt install curl
                     curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
                     sudo apt update
-                    sudo apt install ros-noetic-ros-base
+                    sudo apt install ros-melodic-ros-base
 
-                    source /opt/ros/noetic/setup.bash
+                    source /opt/ros/melodic/setup.bash
                     check_node() {
                         local node_name=$1
                         rosnode list | grep -q "/$node_name"
@@ -41,14 +41,16 @@ jobs:
                             exit 1
                         fi
                     }
+
                     check_topic() {
                         local topic_name=$1
-                        local pub_count=$(rostopic info /$topic_name | grep "Publisher count:" | awk '{print $3}')
-                        local sub_count=$(rostopic info /$topic_name | grep "Subscription count:" | awk '{print $3}')
-                        if [ "$pub_count" -gt 0 ] && [ "$sub_count" -gt 0 ]; then
-                            echo "$topic_name has publishers and subscribers."
+                        local pub_name=$2
+                        local sub_name=$3
+                        rostopic info /$topic_name | grep -E "$pub_name|$sub_name"
+                        if [ $? -eq 0 ]; then
+                            echo "$$topic_name has publisher $pub_name and subscriber $sub_name."
                         else
-                            echo "Error - $topic_name has no publishers or subscribers."
+                            echo "Error - $topic_name does not have pub/sub"
                             exit 1
                         fi
                     }
@@ -60,7 +62,7 @@ jobs:
 
                     check_node talker
                     check_node listener
-                    check_topic chatter
+                    check_topic chatter talker listener
                     kill $pid
 
                     echo "All checks passed successfully."
