fix name variable

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -41,9 +41,9 @@ jobs:
                         local error_code=0
 
                         while true; do
-                            error_code=$(rosnode list | grep -q "/$name"; echo $?)
+                            error_code=$(rosnode list | grep -q "/$node_name"; echo $?)
                             if [ $error_code -eq 0 ]; then
-                                echo "$name is running."
+                                echo "$node_name is running."
                                 return 0
                             fi
 
@@ -51,7 +51,7 @@ jobs:
                             local elapsed_time=$((current_time - start_time))
 
                             if [ $elapsed_time -ge $timeout ]; then
-                                echo "Error $name is not running."
+                                echo "Error $node_name is not running."
                                 sudo snap stop turtlebot3c-bringup
                                 exit 1
                             fi
